Gradle updates
dblitza/sample.javaee7.jms pull request #1
Opened 2017-10-05 14:27 UTC by cthigh

2017-10-05 14:58 UTC, mattbsox requested changes

2017-10-05 14:58 UTC, mattbsox commented on .gitignore
>  /target/
We should add in the eclipse generated files like .project, .classpath, and .settings to the .gitignore.

2017-10-05 14:58 UTC, mattbsox commented on .settings/.jsdtscope
> +<?xml version="1.0" encoding="UTF-8"?>
remove this eclipse file

2017-10-05 14:58 UTC, mattbsox commented on .gitignore
>  /target/
We should also remove all these eclipse files from the PR

2017-10-05 17:30 UTC, dshimo requested changes
We should remove most of these Eclipse-generated files.

Also there's a comment block in `build.gradle` we could remove

2017-10-05 18:16 UTC, cthigh commented on README.md
> +2. If you are running the sample in WebSphere Liberty Profile follow the instructions in the sections below.
change `WebSphere Liberty Profile` to just `Liberty`

2017-10-05 18:16 UTC, cthigh commented on README.md
> +1. Execute full Gradle build. This will cause Liberty Gradle Plug-in to download and install Liberty profile server.
change to:

Execute the full Gradle build. The Liberty Gradle Plug-in will download and install the Liberty runtime and create the server.

2017-10-05 18:16 UTC, cthigh commented on build.gradle
> +    testServerHttpsPort = '9443'
you can remove the quotes from the port numbers.

2017-10-05 18:16 UTC, cthigh commented on build.gradle
> +//    </profiles>
Let's go ahead and remove this profile stuff.

2017-10-10 15:54 UTC, mattbsox requested changes

2017-10-10 15:54 UTC, mattbsox commented on .classpath
>  <?xml version="1.0" encoding="UTF-8"?>
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .settings/org.eclipse.buildship.core.prefs
> +#Mon Oct 09 12:54:30 CDT 2017
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .settings/org.eclipse.buildship.core.prefs
> +#Mon Oct 09 12:54:30 CDT 2017
and any other .settings files

2017-10-10 15:54 UTC, mattbsox commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .factorypath
> +<factorypath>
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .settings/com.ibm.etools.common.migration.prefs
> +#Mon Oct 02 15:36:44 CDT 2017
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .settings/org.eclipse.buildship.core.prefs
> +#Mon Oct 09 12:54:30 CDT 2017
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .settings/org.eclipse.core.resources.prefs
> +eclipse.preferences.version=1
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .settings/org.eclipse.jdt.apt.core.prefs
> +eclipse.preferences.version=1
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .settings/org.eclipse.jdt.core.prefs
> +eclipse.preferences.version=1
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .settings/org.eclipse.m2e.core.prefs
> +activeProfiles=
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .settings/org.eclipse.wst.common.component
> +<?xml version="1.0" encoding="UTF-8"?><project-modules id="moduleCoreId" project-version="1.5.0">
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .settings/org.eclipse.wst.common.project.facet.core.prefs.xml
> +<root>
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .settings/org.eclipse.wst.common.project.facet.core.xml
> +<?xml version="1.0" encoding="UTF-8"?>
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .settings/org.eclipse.wst.jsdt.ui.superType.container
> +org.eclipse.wst.jsdt.launching.baseBrowserLibrary
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .settings/org.eclipse.wst.jsdt.ui.superType.name
> +Window
remove this file

2017-10-10 15:54 UTC, mattbsox commented on .settings/org.eclipse.wst.validation.prefs
> +disabled=06target
remove this file

2017-10-10 15:54 UTC, mattbsox commented on build.gradle
> +sourceCompatibility = 1.7
Set these 2 compatibility properties to 1.8

2017-10-10 15:54 UTC, mattbsox commented on pom.xml
>                  <groupId>net.wasdev.wlp.maven.plugins</groupId>
The runtime version can be set to 17.0.0.2

2017-10-10 21:56 UTC, merged